name: music-streaming

services: 
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # must own the data folder and be able to read music folder(s). See Permissions below
    restart: unless-stopped
    volumes:
      - "/srv/media/music/data:/data"
      - "/srv/media/music/music-files:/music:ro"
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network